-- UP
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'kirindesk_app') THEN
    CREATE ROLE kirindesk_app WITH LOGIN PASSWORD 'kirindesk_app_dev_password' NOSUPERUSER NOCREATEDB NOCREATEROLE;
  END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO kirindesk_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO kirindesk_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO kirindesk_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kirindesk_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO kirindesk_app;

-- DOWN
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM kirindesk_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM kirindesk_app;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM kirindesk_app;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM kirindesk_app;
REVOKE USAGE ON SCHEMA public FROM kirindesk_app;
DROP ROLE IF EXISTS kirindesk_app;
